version: '3'
services:
    python-apache:
        image: ${HTTPD_VERSION}
        container_name: ${HTTPD_CONTAINER}
        restart: on-failure
        env_file:
            - ".env"
        ports:
            - ${HTTPD_PORT}:80
            - ${HTPPD_REMOTE_DEBUG_PORT}:3500
            - ${HTTPD_DEV_SERVER_PORT}:81
        environment:
            - MYPROJECT=${MYPROJECT}
            - HTTPD_HOST=${HTTPD_HOST}
        volumes: 
            - ./site-config.conf:/etc/apache2/sites-available/000-default.conf
            - ./:/var/www/hello

    python-app:
        container_name: ${PYTHON_CONTAINER}
        restart: on-failure
        user: ${USER_ID}:${GROUP_ID}
        env_file:
            - ".env"
        build:
            context: .
            dockerfile: Dockerfile.python
        networks:
            - ${NETWORK}
        volumes:
            - ./src/hello:/var/www/hello/hello

    python_db:
        image: ${MYSQL_VERSION}
        container_name: ${MYSQL_CONTAINER}
        restart: on-failure
        env_file:
            - ".env"
        build:
            dockerfile: Dockerfile.db.test
            context: .
            args:
                MYSQL_VERSION: ${MYSQL_VERSION}
            # https://github.com/docker-library/mysql/issues/422
            # https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log            
        security_opt:
            - seccomp:unconfined
        ports:
            - ${MYSQL_PORT}:3306
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_LOG_CONSOLE=${MYSQL_LOG_ENABLED}
        volumes:
            - ./scripts:/docker-entrypoint-initdb.d
            - ./my.cnf:/etc/mysql/conf.d/my.cnf            
        networks:
            - ${NETWORK}

    python_db_test:
        image: ${MYSQL_VERSION}
        container_name: ${MYSQL_TEST_CONTAINER}
        restart: on-failure
        env_file:
            - ".env"
        build:
            dockerfile: Dockerfile.db.real
            context: .
            args:
                MYSQL_VERSION: ${MYSQL_VERSION}
            # https://github.com/docker-library/mysql/issues/422
            # https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log
        security_opt:
            - seccomp:unconfined
        ports:
            - ${MYSQL_TEST_PORT}:3306
        environment:
            - MYSQL_DATABASE=${MYSQL_TEST_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_TEST_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_TEST_USER}
            - MYSQL_PASSWORD=${MYSQL_TEST_PASSWORD}
            - MYSQL_LOG_CONSOLE=${MYSQL_LOG_ENABLED}
        networks:
            - ${NETWORK}
        volumes:
            - ./scripts:/docker-entrypoint-initdb.d
            - ./my.cnf:/etc/mysql/conf.d/my.cnf            
networks:
    python_network:

volumes:
    db_volume: