version: '3'
services:
    python-apache:
        image: httpd:2.4.58
        container_name: pyHttpd
        restart: on-failure
        env_file:
            - ".env"
        ports:
            - 8080:80
            - 3501:3500
            - 4701:81
        environment:
            - MYPROJECT=hello
            - HTTPD_HOST=localhost
        volumes: 
            - ./site-config.conf:/etc/apache2/sites-available/000-default.conf
            - ./src/hello:/var/www/hello/hello
        networks:
            - python_network            

    python-app:
        container_name: pyApp
        restart: on-failure
        user: 1000:1000
        env_file:
            - ".env"
        build:
            context: .
            dockerfile: Dockerfile.python
        volumes:
            - ./src/hello:/var/www/hello/hello
        networks:
            - python_network

    python_db:
        image: mysql:8.0
        container_name: pyDb
        restart: on-failure
        env_file:
            - ".env"
        build:
            dockerfile: Dockerfile.db.test
            context: .
            args:
                MYSQL_VERSION: mysql:8.0
            # https://github.com/docker-library/mysql/issues/422
            # https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log            
        security_opt:
            - seccomp:unconfined
        ports:
            - 33060:3306
        environment:
            - MYSQL_DATABASE=hello_db
            - MYSQL_ROOT_PASSWORD=toor
            - MYSQL_USER=dbuser
            - MYSQL_PASSWORD=dbuser
            - MYSQL_LOG_CONSOLE=true
        volumes:
            - ./scripts:/docker-entrypoint-initdb.d
            - ./my.cnf:/etc/mysql/conf.d/my.cnf            
        networks:
            - python_network

    python_db_test:
        image: mysql:8.0
        container_name: pyDbTest
        restart: on-failure
        env_file:
            - ".env"
        build:
            dockerfile: Dockerfile.db.real
            context: .
            args:
                MYSQL_VERSION: mysql:8.0
            # https://github.com/docker-library/mysql/issues/422
            # https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log
        security_opt:
            - seccomp:unconfined
        ports:
            - 33061:3306
        environment:
            - MYSQL_DATABASE=hello_db_test
            - MYSQL_ROOT_PASSWORD=toor
            - MYSQL_USER=dbuser
            - MYSQL_PASSWORD=dbuser
            - MYSQL_LOG_CONSOLE=true
        networks:
            - python_network
        volumes:
            - ./scripts:/docker-entrypoint-initdb.d
            - ./my.cnf:/etc/mysql/conf.d/my.cnf            
networks:
    python_network:

volumes:
    db_volume: